# Generated by Django 5.0.9 on 2024-11-13 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('codigoaula', models.IntegerField(db_column='CodigoAula', primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField(db_column='Capacidad')),
                ('numeroaula', models.IntegerField(db_column='NumeroAula')),
            ],
            options={
                'db_table': 'Aula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('ceduladocente', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='CedulaDocente', max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=50)),
                ('apellido', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Apellido', max_length=50)),
                ('telefono', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Telefono', max_length=20, null=True)),
                ('especialidad', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Especialidad', max_length=50)),
                ('direccion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Direccion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('codigoasignatura', models.IntegerField(db_column='CodigoAsignatura', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=50)),
                ('idasignatura', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='IdAsignatura', max_length=20)),
            ],
            options={
                'db_table': 'Asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('codestudiante', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='CodEstudiante', max_length=50, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre1', max_length=50)),
                ('nombre2', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Nombre2', max_length=50, null=True)),
                ('apellido1', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Apellido1', max_length=50)),
                ('apellido2', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Apellido2', max_length=50, null=True)),
                ('fechanac', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='FechaNac', max_length=100, null=True)),
                ('edad', models.IntegerField(blank=True, db_column='Edad', null=True)),
                ('sexo', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Sexo', max_length=10, null=True)),
                ('cedulaalumno', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='CedulaAlumno', max_length=20, null=True)),
                ('direccionalumno', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='DireccionAlumno', max_length=100, null=True)),
                ('matricula', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Matricula', max_length=20)),
            ],
            options={
                'db_table': 'Estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('codigogrupo', models.IntegerField(db_column='CodigoGrupo', primary_key=True, serialize=False)),
                ('nivelacademico', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='NivelAcademico', max_length=50)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=50)),
            ],
            options={
                'db_table': 'Grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('codigohorario', models.IntegerField(db_column='CodigoHorario', primary_key=True, serialize=False)),
                ('horainicio', models.TimeField(db_column='HoraInicio')),
                ('horafin', models.TimeField(db_column='HoraFin')),
            ],
            options={
                'db_table': 'Horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('codigoturno', models.IntegerField(db_column='CodigoTurno', primary_key=True, serialize=False)),
                ('horario', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Horario', max_length=50)),
            ],
            options={
                'db_table': 'Turno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('codigotutor', models.IntegerField(db_column='CodigoTutor', primary_key=True, serialize=False)),
                ('nombretutor', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='NombreTutor', max_length=50)),
                ('cedulatutor', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='CedulaTutor', max_length=20)),
            ],
            options={
                'db_table': 'Tutor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignacionaula',
            fields=[
                ('codigoaula', models.OneToOneField(db_column='CodigoAula', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='RegistroAcademico.aula')),
            ],
            options={
                'db_table': 'AsignacionAula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignaciondocente',
            fields=[
                ('ceduladocente', models.OneToOneField(db_column='CedulaDocente', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='RegistroAcademico.docente')),
            ],
            options={
                'db_table': 'AsignacionDocente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscribe',
            fields=[
                ('IdInscribe', models.AutoField(primary_key=True, serialize=False)),
                ('fechainscripcion', models.DateField(db_column='FechaInscripcion')),
                ('codestudiante', models.ForeignKey(db_column='CodEstudiante', on_delete=django.db.models.deletion.CASCADE, to='RegistroAcademico.estudiante')),
                ('codigoasignatura', models.ForeignKey(db_column='CodigoAsignatura', on_delete=django.db.models.deletion.CASCADE, to='RegistroAcademico.asignatura')),
            ],
            options={
                'db_table': 'Inscribe',
                'unique_together': {('codestudiante', 'codigoasignatura')},
            },
        ),
        migrations.CreateModel(
            name='Registronotas',
            fields=[
                ('codestudiante', models.ForeignKey(db_column='CodEstudiante', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='RegistroAcademico.estudiante')),
                ('periodoacademico', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='PeriodoAcademico', max_length=20)),
                ('parcial1', models.DecimalField(blank=True, db_column='Parcial1', decimal_places=2, max_digits=5, null=True)),
                ('parcial2', models.DecimalField(blank=True, db_column='Parcial2', decimal_places=2, max_digits=5, null=True)),
                ('parcial3', models.DecimalField(blank=True, db_column='Parcial3', decimal_places=2, max_digits=5, null=True)),
                ('parcial4', models.DecimalField(blank=True, db_column='Parcial4', decimal_places=2, max_digits=5, null=True)),
                ('notafinal', models.DecimalField(blank=True, db_column='NotaFinal', decimal_places=2, max_digits=5, null=True)),
                ('codigoasignatura', models.ForeignKey(db_column='CodigoAsignatura', on_delete=django.db.models.deletion.CASCADE, to='RegistroAcademico.asignatura')),
            ],
            options={
                'db_table': 'RegistroNotas',
                'unique_together': {('codestudiante', 'codigoasignatura', 'periodoacademico')},
            },
        ),
    ]
