# Generated by Django 5.0.9 on 2024-11-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAcademico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscribe',
            options={'managed': False},
        ),
    ]
