# Generated by Django 5.0.9 on 2024-11-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAcademico', '0002_alter_inscribe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscribe',
            options={},
        ),
    ]
