# Generated by Django 5.0.9 on 2024-11-10 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroAcademico', '0004_alter_inscribe_codestudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscribe',
            name='codestudiante',
            field=models.ForeignKey(db_column='CodEstudiante', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='RegistroAcademico.estudiante'),
        ),
    ]
